on: workflow_dispatch

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - shell: bash
      name: test demo
      working-directory: ./demo
      run: |
        ./lib.sh

    - shell: bash
      name: build breakout
      working-directory: ./breakout
      run: |
        ./lib.sh

