on: workflow_dispatch

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - shell: bash
      name: build test platform
      working-directory: ./platform
      run: |
        ./lib.sh

    - shell: bash
      name: build test demo
      working-directory: ./demo
      run: |
        ./lib.sh

    - shell: bash
      name: build breakout
      working-directory: ./breakout
      run: |
        ./lib.sh

    - shell: bash
      name: build test sprite-editor 
      working-directory: ./sprite-editor
      run: |
        ./lib.sh

    - shell: bash
      name: build obby-1 
      working-directory: ./obby-1
      run: |
        ./lib.sh


